SELECT * FROM NORMAN.CCIORDER ORDER BY C_ID;
SELECT * FROM NORMAN.CCIITEM ORDER BY QTY;
SELECT * FROM NORMAN.CCIITEM,NORMAN.CCIORDER
WHERE CCIITEM.O_ID = NORMAN.CCIORDER.O_ID
AND NORMAN.CCIORDER.DATE_COMP IS NULL;
SELECT * FROM NORMAN.CCIORDER WHERE C_ID
IN (SELECT C_ID FROM NORMAN.CCICUSTOMER WHERE C_NAME = 'george');





SELECT * FROM NORMAN.CCICUSTOMER
LEFT OUTER JOIN NORMAN.CCIORDER
ON CCIORDER.C_ID=CCICUSTOMER.C_ID;


SELECT NORMAN.CCICUSTOMER.C_NAME,NORMAN.CCIORDER.DATE_REC FROM
NORMAN.CCICUSTOMER JOIN NORMAN.CCIORDER ON NORMAN.CCIORDER.DATE_REC='jan';






